-- Presence / "who is online" + the welcome-broadcast dedupe log.
-- Run once in the Supabase SQL editor (service role). Idempotent — safe to re-run.
--
-- Why: there was no last-seen tracking of any kind. The only signal in the system was
-- Supabase's own auth.users.last_sign_in_at, which (a) only updates at login, so it can't
-- answer "online now", and (b) exists only for owners/admins — tenants are not Supabase
-- users at all, they carry a stateless HMAC JWT with no server-side record.

-- 1. Presence, one row per user per device ---------------------------------------------
-- user_id is TEXT, not uuid: it holds either an auth.users.id (owner/admin) or a tenants.id.
-- Same reasoning as device_tokens.user_id, which FIX_PUSH_AND_TENANT_MOVE.sql widened to text
-- for exactly this. Deliberately NOT a foreign key — see the ADD_STAFF.sql rationale: a
-- missing or lagging parent row must never make a heartbeat un-writable.
create table if not exists public.user_presence (
  user_id       text        not null,
  device_id     text        not null,   -- stable per-install id generated by the client
  role          text        not null,   -- 'owner' | 'admin' | 'tenant'
  platform      text,                   -- 'web' | 'android'
  user_agent    text,
  first_seen_at timestamptz not null default now(),
  last_seen_at  timestamptz not null default now(),
  primary key (user_id, device_id)
);

-- "Who is online" scans by recency; the admin directory looks up by user.
create index if not exists user_presence_last_seen_idx on public.user_presence (last_seen_at desc);
create index if not exists user_presence_user_idx      on public.user_presence (user_id);
create index if not exists user_presence_role_idx      on public.user_presence (role);

comment on table public.user_presence is
  'Heartbeat log. One row per (user, device). "Online" = last_seen_at within the last 5 minutes.';

-- 2. Welcome-broadcast dedupe -----------------------------------------------------------
-- Lets the admin target "users who have never been welcomed" and makes a second send skip
-- anyone already covered, so a manual re-send is safe.
create table if not exists public.welcome_dispatch (
  user_id   text primary key,   -- owner uid or tenant id
  role      text not null,
  notice_id uuid,
  sent_at   timestamptz not null default now()
);

create index if not exists welcome_dispatch_sent_at_idx on public.welcome_dispatch (sent_at desc);

-- 3. RLS: same posture as ENABLE_RLS.sql — on, with NO policies, grants revoked. The backend
-- reaches these with the service-role key, which bypasses RLS entirely.
alter table public.user_presence    enable row level security;
alter table public.welcome_dispatch enable row level security;
revoke all on public.user_presence    from anon, authenticated;
revoke all on public.welcome_dispatch from anon, authenticated;
