-- Partial rent payments: a rent invoice can now be settled in installments instead of
-- all-or-nothing. Run once in the Supabase SQL editor (service role). Idempotent — safe to re-run.
--
-- Self-contained: it re-applies ADD_BILLING_PAID_AT.sql's column (idempotently), so the two can
-- be run in either order, and it skips the Accounts step when that module isn't installed.
--
-- Why a child table rather than more columns on billing_ledgers: a tenant may pay ৳5,000 now and
-- the rest a week later, and the receipt has to show each payment with its own date. That is a
-- list, not a pair of columns. Same shape as staff_payments — an ad-hoc log, not a schedule.
--
-- billing_payments rows are the TRUTH. billing_ledgers.amount_paid / payment_status / paid_at are
-- derived from them by recalcLedger() in lib/billing.ts after every insert and delete, and are
-- written by nothing else. That is what keeps the existing dashboard sums correct.
--
-- owner_id is intentionally NOT a foreign key (same rationale as staff / reminders /
-- contact_messages: a missing user_profiles stub must never make a payment un-writable).

-- =====================================================================================
-- 1. BILLING PAYMENTS (installment log)
-- =====================================================================================
-- NOTE ON ID TYPES: the base schema was built by hand in the Supabase dashboard and its key
-- columns are NOT all uuid — billing_ledgers.id is character varying, the same way properties.id
-- is text (see ADD_STAFF.sql's property_id). Every id here is a UUID *string* generated by the
-- app (crypto.randomUUID) and sent over PostgREST as text either way, so the referencing columns
-- are declared text to match whatever the parent actually is. Declaring them uuid fails with
-- 42804 "Key columns are of incompatible types".
create table if not exists public.billing_payments (
  id          uuid primary key,
  payment_no  bigint generated always as identity,   -- human-facing reference, e.g. "#3"
  ledger_id   text not null references public.billing_ledgers (id) on delete cascade,
  -- Denormalised so ownership is enforced on the payment row itself rather than trusted
  -- through ledger_id, and so the owner-wide payment list needs no join.
  owner_id    text not null,
  -- Denormalised for the same reason on the tenant side: a tenant reads their own payments
  -- without being able to reach anyone else's ledger.
  tenant_id   text,
  amount      numeric(12, 2) not null check (amount > 0),
  paid_on     date not null,
  method      text not null default 'cash'
                check (method in ('cash', 'bkash', 'nagad', 'bank', 'other')),
  note        text,
  created_at  timestamptz not null default now()
);

-- paid_on ascending on the ledger index: the receipt numbers payments 1st, 2nd, 3rd in date order.
create index if not exists billing_payments_ledger_idx on public.billing_payments (ledger_id, paid_on);
create index if not exists billing_payments_owner_idx  on public.billing_payments (owner_id, paid_on desc);
create index if not exists billing_payments_tenant_idx on public.billing_payments (tenant_id, paid_on desc);

-- =====================================================================================
-- 2. DERIVED COLUMNS ON THE PARENT
-- =====================================================================================
-- Same statement as ADD_BILLING_PAID_AT.sql, repeated here so this file does not depend on the
-- order the two were run in. Idempotent — a no-op if that migration already added it. The
-- backfill below reads paid_at, and without the column the whole script would roll back.
alter table public.billing_ledgers
  add column if not exists paid_at timestamptz;

-- Cached sum of the payments. Denormalised deliberately: the owner dashboard's "Outstanding"
-- and "Collected" figures are computed over every ledger on every render, and re-summing a
-- child table client-side for each one is the wrong trade.
alter table public.billing_ledgers
  add column if not exists amount_paid numeric(12, 2) not null default 0;

-- =====================================================================================
-- 3. ALLOW THE 'partial' STATUS
-- =====================================================================================
-- billing_ledgers was built by hand in the Supabase dashboard and has no DDL in this repo, so
-- there may be a hand-made CHECK on payment_status under an unknown name. If there is, it would
-- reject every 'partial' write with a constraint violation and the feature would fail only at
-- runtime. Drop whatever is there by name, then add a known one.
do $$
declare c record;
begin
  for c in
    select con.conname
      from pg_constraint con
      join pg_class rel     on rel.oid = con.conrelid
      join pg_namespace ns  on ns.oid  = rel.relnamespace
     where ns.nspname = 'public'
       and rel.relname = 'billing_ledgers'
       and con.contype = 'c'
       and pg_get_constraintdef(con.oid) ilike '%payment_status%'
  loop
    execute format('alter table public.billing_ledgers drop constraint %I', c.conname);
  end loop;
end $$;

-- NOT VALID, then validated separately: adding it validating would scan every existing row, and
-- one legacy row with an unexpected status would abort — and with it this whole file. NOT VALID
-- still enforces the constraint on every new write, which is all this needs to do.
alter table public.billing_ledgers
  add constraint billing_ledgers_payment_status_check
  check (payment_status in ('unpaid', 'sent', 'partial', 'paid')) not valid;

do $$
begin
  alter table public.billing_ledgers validate constraint billing_ledgers_payment_status_check;
exception when others then
  raise notice 'Existing rows hold a payment_status outside (unpaid, sent, partial, paid); the constraint is active for new writes but was left unvalidated. Check with: select distinct payment_status from public.billing_ledgers;';
end $$;

-- =====================================================================================
-- 4. BACKFILL (not optional)
-- =====================================================================================
-- Without this, every invoice already marked paid has no payment rows, so the first recalc
-- flips it back to 'unpaid' and the owner's "Collected" figure collapses to zero.
-- One payment row per already-paid invoice, dated from paid_at (or created_at when the
-- paid_at migration ran after the invoice was settled).
insert into public.billing_payments (id, ledger_id, owner_id, tenant_id, amount, paid_on, method, note)
-- Explicit ::text on the id columns: billing_ledgers' key columns may be varchar or uuid
-- depending on how each was created by hand, and this makes the insert work either way.
select gen_random_uuid(),
       l.id::text,
       l.created_by_owner::text,
       l.tenant_id::text,
       l.total_payable,
       coalesce(l.paid_at::date, l.created_at::date),
       'cash',
       'Recorded before installments were supported'
  from public.billing_ledgers l
 where l.payment_status = 'paid'
   and not exists (select 1 from public.billing_payments p where p.ledger_id = l.id);

update public.billing_ledgers l
   set amount_paid = coalesce((select sum(p.amount) from public.billing_payments p where p.ledger_id = l.id), 0);

-- =====================================================================================
-- 5. RE-POINT THE ACCOUNTS AUTO-ROWS
-- =====================================================================================
-- Rent income is now booked ONE ROW PER INSTALLMENT, so account_transactions.source_ref holds a
-- billing_payments.id where it used to hold a billing_ledgers.id. Without this the old
-- whole-invoice rows never match a reversal again and would double-count beside the new ones.
-- (source stays 'billing', so the (source, source_ref) partial unique index needs no change —
-- it now correctly permits many rows per invoice, one per payment.)
-- Guarded: ADD_ACCOUNTS.sql may not have been run on this database, and an error here would roll
-- back this entire file (the Supabase SQL editor runs a script as one transaction).
do $$
begin
  if to_regclass('public.account_transactions') is not null then
    update public.account_transactions t
       set source_ref = p.id::text
      from public.billing_payments p
     where t.source = 'billing'
       and t.source_ref = p.ledger_id;
  else
    raise notice 'account_transactions not present — skipping the Accounts re-point (run ADD_ACCOUNTS.sql first if you use the Accounts add-on).';
  end if;
end $$;

-- =====================================================================================
-- 6. RLS
-- =====================================================================================
-- Same posture as ENABLE_RLS.sql / ADD_STAFF.sql: RLS on with NO policies (deny-all to anon and
-- authenticated) and the default API grants revoked. The backend reaches this table with the
-- service-role key, which bypasses RLS entirely.
alter table public.billing_payments enable row level security;

revoke all on public.billing_payments from anon, authenticated;
